# Generated by Django 4.2.5 on 2025-02-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_extrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrato',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
