# Generated by Django 4.2.5 on 2025-02-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_extrato_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contareceber',
            name='numero_parcela',
            field=models.IntegerField(default=1),
        ),
    ]
