# Generated by Django 4.2.5 on 2025-02-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_extrato_metodo_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrato',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
