# Generated by Django 4.2.5 on 2025-02-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_extrato_data_vencimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrato',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('nao_pago', 'Não Pago')], max_length=10, null=True),
        ),
    ]
