# Generated by Django 4.2.5 on 2025-02-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0007_extrato_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrato',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('nao_pago', 'Não Pago')], default='pendente', max_length=10),
        ),
    ]
