# Generated by Django 4.2.5 on 2025-02-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0008_alter_extrato_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contareceber',
            name='metodo_pagamento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
