# Generated by Django 4.2.5 on 2025-02-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0009_contareceber_metodo_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='metodo_pagamento',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='numero_parcela',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
