# Generated by Django 4.2.5 on 2025-03-10 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_parcelapedido'),
        ('financeiro', '0010_contapagar_metodo_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.pedidocompra'),
        ),
    ]
