# Generated by Django 4.2.5 on 2025-03-26 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0011_contapagar_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrato',
            name='data_vencimento',
        ),
    ]
