# Generated by Django 4.2.5 on 2025-05-09 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0004_parcelapedido'),
        ('financeiro', '0012_remove_extrato_data_vencimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='contareceber',
            name='parcela_pedido',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conta_receber', to='venda.parcelapedido'),
        ),
    ]
