# Generated by Django 4.2.5 on 2025-05-09 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0013_contareceber_parcela_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contareceber',
            name='parcela_pedido',
        ),
    ]
