# Generated by Django 4.2.5 on 2025-06-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0014_remove_contareceber_parcela_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='editavel',
            field=models.BooleanField(default=False),
        ),
    ]
