# Generated by Django 4.2.5 on 2025-06-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0015_contapagar_editavel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contapagar',
            name='editavel',
        ),
        migrations.AddField(
            model_name='contareceber',
            name='editavel',
            field=models.BooleanField(default=False),
        ),
    ]
