# Generated by Django 4.2.5 on 2025-06-12 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0009_pedido_condicao_pagamento'),
        ('financeiro', '0016_remove_contapagar_editavel_contareceber_editavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contareceber',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='venda.pedido'),
        ),
    ]
