# Generated by Django 4.2.5 on 2025-06-16 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0017_contareceber_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrato',
            name='conta_pagar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.contapagar'),
        ),
        migrations.AddField(
            model_name='extrato',
            name='conta_receber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.contareceber'),
        ),
    ]
