# Generated by Django 4.2.5 on 2025-06-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0018_extrato_conta_pagar_extrato_conta_receber'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='editavel',
            field=models.BooleanField(default=False),
        ),
    ]
