# Generated by Django 4.2.5 on 2025-10-07 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0019_contapagar_editavel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('banco', models.CharField(max_length=100)),
                ('agencia', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_conta', models.CharField(max_length=50)),
                ('tipo_conta', models.CharField(choices=[('corrente', 'Conta Corrente'), ('poupanca', 'Poupança')], max_length=20)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
