# Generated by Django 4.2.5 on 2025-10-07 19:05

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0020_contabancaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacaoBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('saldo_apos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='financeiro.contabancaria')),
            ],
        ),
    ]
