# Generated by Django 4.2.5 on 2025-10-07 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0021_movimentacaobancaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='conta_bancaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contapagar', to='financeiro.contabancaria'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='conta_bancaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contareceber', to='financeiro.contabancaria'),
        ),
    ]
