# Generated by Django 4.2.5 on 2025-10-08 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0022_contapagar_conta_bancaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrato',
            name='conta_bancaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extratos', to='financeiro.contabancaria'),
        ),
    ]
