# Generated by Django 4.2.5 on 2025-10-10 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0023_extrato_conta_bancaria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacaobancaria',
            name='saldo_apos',
        ),
    ]
