# Generated by Django 4.2.5 on 2024-09-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='data_pedido',
            field=models.DateField(blank=True, null=True),
        ),
    ]
