# Generated by Django 4.2.5 on 2023-10-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='quantidade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
