# Generated by Django 4.2.5 on 2023-10-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0002_carrinho_quantidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='View_Carrinho',
            fields=[
                ('produto_id', models.IntegerField(blank=True, null=True)),
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('nome', models.CharField(max_length=50)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('qt_itens', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'View_Carrinho',
                'managed': False,
            },
        ),
    ]
