# Generated by Django 4.2.5 on 2024-10-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0002_pedido_data_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='metodo_pagamento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='parcelas',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
