# Generated by Django 4.2.5 on 2023-11-01 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0003_view_carrinho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('produto_id', models.IntegerField(blank=True, null=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
        ),
    ]
