# Generated by Django 4.2.5 on 2023-11-01 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0004_pedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='user_id',
            new_name='nr_pedido',
        ),
    ]
