# Generated by Django 4.2.5 on 2025-05-09 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0005_pedidoitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PedidoItem',
        ),
    ]
