# Generated by Django 4.2.5 on 2025-05-11 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0006_delete_pedidoitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParcelaPedido',
        ),
    ]
