# Generated by Django 4.2.5 on 2023-11-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0006_view_pedidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='View_Pedido',
            fields=[
                ('produto_id', models.IntegerField(blank=True, null=True)),
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('nr_pedido', models.IntegerField(blank=True, null=True)),
                ('nome_produto', models.CharField(max_length=50)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'View_pedido',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='View_Pedidos',
        ),
    ]
