# Generated by Django 4.2.5 on 2023-11-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0007_view_pedido_delete_view_pedidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
