# Generated by Django 4.2.5 on 2023-11-06 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0008_pedido_user_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='view_pedido',
            table='View_Pedido',
        ),
    ]
