# Generated by Django 4.2.5 on 2025-06-12 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condicaoPagamento', '0001_initial'),
        ('venda', '0008_parcelapedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='condicao_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='condicaoPagamento.condicaopagamento'),
        ),
    ]
