# Generated by Django 4.2.5 on 2025-06-13 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0010_alter_carrinho_produto_id_alter_pedido_produto_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrinho',
            old_name='produto_id',
            new_name='produto',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='produto_id',
            new_name='produto',
        ),
    ]
