# Generated by Django 4.2.5 on 2025-10-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0011_rename_produto_id_carrinho_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='condicao_desconto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='condicao_juros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='condicao_nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='condicao_parcelas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='condicao_tipo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
