# Generated by Django 4.2.5 on 2025-10-11 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0003_rename_data_admissão_funcionarios_data_admissao'),
        ('venda', '0012_pedido_condicao_desconto_pedido_condicao_juros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionario.funcionarios'),
        ),
    ]
