# Generated by Django 4.2.5 on 2025-10-14 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0013_pedido_funcionario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParcelaPedido',
        ),
    ]
