# Generated by Django 4.2.5 on 2025-10-14 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_parcelapedido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParcelaPedido',
        ),
    ]
