# Generated by Django 4.2.5 on 2025-05-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('cpf', models.CharField(blank=True, max_length=14, unique=True)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('data_admissão', models.DateField()),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('endereco', models.CharField(blank=True, max_length=200)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'funcionário',
                'verbose_name_plural': 'funcionários',
                'ordering': ['nome'],
            },
        ),
    ]
