# Generated by Django 4.2.5 on 2025-05-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionarios',
            name='data_admissão',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
