# Generated by Django 4.2.5 on 2025-05-06 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0002_alter_funcionarios_data_admissão'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionarios',
            old_name='data_admissão',
            new_name='data_admissao',
        ),
    ]
