# Generated by Django 4.2.5 on 2025-03-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CondicaoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('tipo_pagamento', models.CharField(choices=[('credito', 'Cartão de Crédito'), ('debito', 'Cartão de Débito'), ('pix', 'Pix'), ('boleto', 'Boleto Bancário'), ('transferencia', 'Transferência Bancária'), ('dinheiro', 'Dinheiro')], max_length=20)),
                ('parcelas', models.IntegerField(default=1)),
                ('juros', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('intervalo_parcelas', models.IntegerField(default=30, help_text='Dias entre parcelas')),
                ('desconto', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Condição de Pagamento',
                'verbose_name_plural': 'Condições de Pagamento',
            },
        ),
    ]
