# Generated by Django 4.2.5 on 2024-08-19 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_alter_produto_descricao_alter_produto_preco'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['nome'], 'verbose_name': 'produto', 'verbose_name_plural': 'produto'},
        ),
    ]
