# Generated by Django 4.2.5 on 2024-10-02 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_alter_produto_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['nome_categoria'],
            },
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['nome'], 'verbose_name': 'produto', 'verbose_name_plural': 'produtos'},
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria_nome',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
