# Generated by Django 4.2.5 on 2024-10-02 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_categoria_alter_produto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome'], 'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='nome_categoria',
            new_name='nome',
        ),
    ]
