# Generated by Django 4.2.5 on 2025-06-12 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria_nome',
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='estoque.categoria'),
        ),
    ]
