# Generated by Django 4.2.5 on 2025-10-14 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelatorioVenda',
        ),
    ]
