# Generated by Django 4.2.5 on 2024-09-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0002_fornecedor_cpf_fornecedor_tipo_pessoa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(blank=True, default='Não Possui', max_length=18, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cpf',
            field=models.CharField(blank=True, default='Não Possui', max_length=14, null=True, unique=True),
        ),
    ]
